name: 'Kenna: Get Malware Samples For CVE - Javascript Action'
description: 'This GitHub Action checks a CVE security alert (e.g. from Dependabot) for known malware exploits using the Cisco Kenna Security VI+ API and a NodeJS GitHub Action. Do not forget the environment variables KENNA_API_KEY and CVE_ID'
author: 'Christopher van der Made'

branding:
  icon: "bell"
  color: "black"

outputs:
  returned_kenna_data: # id of output
    description: 'The data returned from the Cisco Kenna VI+ API'

runs:
  using: 'node16'
  main: 'kenna_cve_action.js'
