name: 'Webex: Post Message to Room - Javascript Action'
description: 'Send Webex notifications from GitHub actions! Do not forget the environment variables TOKEN, ROOMID and MESSAGE'
author: 'Christopher van der Made'

branding:
  icon: "bell"
  color: "black"

runs:
  using: 'node16'
  main: 'webex_action.js'
